name: Rspec

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    name: RSpec
    runs-on: ubuntu-latest
    container:
      image: damisul/bybe-base:latest
    services:
      mysql:
        image: mysql:8.0.36
        env:
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      elasticsearch:
        image: elasticsearch:7.17.8
        env:
          discovery.type: single-node
          xpack.security.enabled: false
          ingest.geoip.downloader.enabled: false
          action.destructive_requires_name: false
          ES_JAVA_OPTS: -Xms1024m -Xmx1024m
      redis:
        image: redis:7.2.3
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Verify MySQL connection from host
        run: |
          mysql --host mysql --port 3306 -uroot -proot -e "SHOW GRANTS FOR 'root'@'localhost'"
      - name: Update Configuration
        run: |
          cp ./.github/workflows/rspec_config/* ./config
          echo ELASTICSEARCH_HOST=elasticsearch:9200 > ./.env.test.local
          echo DATABASE_URL=mysql2://root:root@mysql:3306/bybe_test >> ./.env.test.local
          echo REDIS_URL=redis://redis:6379/1 >> ./.env.test.local
      - name: Setup DB
        run: |
          bin/rails db:create RAILS_ENV=test
          bin/rails db:migrate RAILS_ENV=test
      - name: Run tests
        run: |
          bundle exec rspec --exclude-pattern "spec/system/**/*_spec.rb"
